### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by JulyStar-Lv** [FranzLiszt-1847/MagicPlayer#1]
App默认Base Url 登录code 460
https://github.com/23233/NeteaseCloudMusicApi，
布置了docker版本的也无法登录；
能否提供下您使用的网易云音乐API代码呢？

**Comment by FranzLiszt-1847** [comment]
您好，感谢您的关注！由于最近网易十分注重版权，故各大引用此API的开发者，大部分都收到律师函警告。故此接口或许已被网易官方所管控或者修改。
2024年3月25日


| |
FranzLiszt1847
|
|
***@***.***
|


---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年03月25日 20:41 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> |
| 主题 | [FranzLiszt-1847/MagicPlayer] 登录失败 (Issue #1) |

App默认Base Url 登录code 460
https://github.com/23233/NeteaseCloudMusicApi，
布置了docker版本的也无法登录；
能否提供下您使用的网易云音乐API代码呢？

**Comment by JulyStar-Lv** [comment]
好的，感谢反馈！
